name: "Build MacOS x86"
on: workflow_dispatch
jobs:
    runbuild:
        name: "Build MacOS x86"
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                go-version: '1.21.5'
            - run: brew tap scripthaus-dev/scripthaus
            - run: brew install scripthaus
            - run: yarn --frozen-lockfile
            - run: scripthaus run build-package


