name: TestDriver.ai Regression Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 21 * * *" # every day at 9pm
  workflow_dispatch:

jobs:
  test:
    name: "TestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: dashcamio/testdriver@main
        id: testdriver
        # note that .testdriver/prerun.sh runs before this, so the app has launched already
        with:
          prompt: |
            2. click "Continue"
            2. focus the Wave input with the keyboard shorcut Command + I
            3. type 'ls' into the input
            4. press return
            5. validate Wave shows the result of 'ls'
