name: TestDriver.ai Regression Testing (test)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 21 * * *" # every day at 9pm
  workflow_dispatch:

jobs:
  test:
    name: "TestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: dashcamio/testdriver@main
        id: testdriver
        # note that .testdriver/prerun.sh runs before this, so the app has launched already
        with:
          version: v2.9.4
          prerun: |
            rm ~/Desktop/WITH-LOVE-FROM-AMERICA.txt
            cd ~/actions-runner/_work/testdriver/testdriver/
            brew install go
            brew tap scripthaus-dev/scripthaus
            brew install scripthaus
            npm install -g yarn
            scripthaus run build-backend
            echo "Yarn"
            yarn
            echo "Rebuild"
            scripthaus run electron-rebuild
            echo "Webpack"
            scripthaus run webpack-build
            echo "Starting Electron"
            scripthaus run electron 1>/dev/null 2>&1 &
            echo "Electron Done"
            exit
          prompt: |
            2. click "Create new tab"
            2. focus the Wave input with the keyboard shorcut Command + I
            3. type 'ls' into the input
            4. press return
            5. validate Wave shows the result of 'ls'
